all:
	gcc -g -Wall -Werror main.c

cpp:
	g++ -g -Wall -Werror main.cc

clean:
	@rm -rf *.*~ \
		*.*.swo \
		*~ \
		*un~ \
		*.*.un \
		*.*.*.un~ \
		*.*.un~ \
		.*.un~ \
		.*.*.un~ \
		a.exe \
		a.out
